### ISSUE TITLE
Transforming rectilinear to any other projection results in error

### ISSUE THREAD

**Issue by alapsansky** [wmoreirae/photonbend#1]
I noticed that there is an issue when transforming an image from rectilinear projection to any other type of projection due to an issue on line 88 of photonbend\core\lens.py. 

    if theta < 0:
        raise ValueError("The angle theta cannot be negative")
    if theta > to_radians(89):
        raise ValueError(
            "The Rectilinear lens can't handle FoV larger than 179 degrees"
        )
    return np.tan(theta)

Specifically, the computation of theta for a rectilinear lens results in a multi-element array that cannot be compared to 0 or to_radians(89). It is unclear to me why theta is multi-element. However, deleting these checks from `lens.py` causes the expected transformation, as verified by viewing the original equidistant image and recomputed equidistant image from a rectilinear transformation.

Full error output:
(prosilica) C:\Users\tonyl\Downloads\photonbend-main\photonbend-main\examples>photonbend alter-photo --itype inscribed --otype inscribed --ilens rectilinear --olens equidistant --ifov 140 --ofov 360 rectlinear-full_new.jpg equidistant_new.jpg
Traceback (most recent call last):
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\tonyl\anaconda3\envs\prosilica\Scripts\photonbend.exe\__main__.py", line 7, in <module>
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\site-packages\photonbend\scripts\commands\alter_photo.py", line 154, in alter_photo
    mapped_array = source_image.process_coordinate_map(destiny_map)
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\site-packages\photonbend\core\projection.py", line 220, in process_coordinate_map
    positions_x, positions_y = self._make_cartesian_map(latitude, longitude)
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\site-packages\photonbend\core\projection.py", line 251, in _make_cartesian_map
    distance = self.forward_lens(latitude) * self.f_distance
  File "C:\Users\tonyl\anaconda3\envs\prosilica\lib\site-packages\photonbend\core\lens.py", line 88, in _rectilinear
    if theta < 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Code to recreate:

`photonbend alter-photo --itype inscribed --otype full --ilens equidistant --olens rectilinear --ifov 360 --ofov 140 equidistant.jpg rectlinear-full_new.jpg`

`photonbend alter-photo --itype full --otype inscribed --ilens rectilinear --olens equidistant --ifov 140 --ofov 360 rectlinear-full_new.jpg equidistant_new.jpg`

![original_vs_recomputed](https://user-images.githubusercontent.com/29434312/230138396-4fdc5af5-21cd-4668-b3a8-b5f2f7fa5483.png)

**Comment by wmoreirae** [comment]
Made a correction to the rectilinear lens code. Should be working correctly now.

About your comment:

> Specifically, the computation of theta for a rectilinear lens results in a multi-element array that cannot be compared to 0 or to_radians(89). It is unclear to me why theta is multi-element. However, deleting these checks from lens.py causes the expected transformation, as verified by viewing the original equidistant image and recomputed equidistant image from a rectilinear transformation.

The lens code was cleverly designed to handle both individual floating-point values and numpy arrays of floats, allowing for versatile processing capabilities. This design choice enables the lens code's utilization in tasks such as processing the image field of view and facilitating conversions between various image types.

In the specific scenario described, Theta takes on a multielement nature due to it being a numpy array. This array serves as a map, effectively capturing the angular coordinates of the target image.
The rectilinear lens code incorporates angle validations as part of its mechanism (as it has inherent angle limitations). These validations play a role in regulating the maximum field of view for rectilinear images, a function that is invoked through a distinct code pathway. 

Addressing the bug you highlighted, a novel validation step has been introduced. This step discerns between processing a single float and handling a numpy array. Additionally, the code intelligently labels angles exceeding the 0 to 89-degree range as invalid, signified by the use of np.nan, particularly when dealing with numpy arrays. This precautionary measure averts the generation of erroneous images stemming from out-of-bounds angle values.

Here is the image generated after the corrections by following your recipe:

`photonbend alter-photo --itype full --otype inscribed --ilens rectilinear --olens equidistant --ifov 140 --ofov 360 rectlinear-full_new.jpg equidistant_new.jpg`
 
![equidistant_new](https://github.com/wmoreirae/photonbend/assets/52007784/25b6d224-ce35-4be5-a582-68624e5b4eea)

Thanks for the report!
